### PR TITLE
Allow more complex filters with AND and OR mixed for the same query.

### PR DESCRIPTION
**Pull request by utking**

### CODE REVIEW

**Comment by legomolina** [comment]
Can you post some examples using new features?
Thanks

**Comment by utking** [comment]
Sure.
$result = MyModel::all()->where()->andFilter('field', '=', 'value')->execute();
results to SELECT * FROM MyModel WHERE (field = 'value');

$result = MyModel::all()->where()->andFilter([
  ['field1', '=', 'value'],
  ['field2', 'LIKE', '%a%'],
])->execute();
results to SELECT * FROM MyModel WHERE (field1 = 'value' AND field2 LIKE '%a%');

$result = MyModel::all()->where()
->andFilter([
  ['field1', '=', 'value'],
  ['field2', 'LIKE', '%a%'],
])
->and()
->orFilter([
  ['field3', '=', 18],
  ['field3', '=', 19],
])
->execute();
results to SELECT * FROM MyModel WHERE (field1 = 'value' AND field2 LIKE '%a%') AND (field3 = 18 OR field3 = 19);

$result = MyModel::all()->where()
->andFilter([
  ['field1', '=', 'value'],
  ['field2', 'LIKE', '%a%'],
])
->or()
->andFilter([
  ['field3', '=', 18],
  ['field4', '=', 19],
])
->execute();
results to SELECT * FROM MyModel WHERE (field1 = 'value' AND field2 LIKE '%a%') OR (field3 = 18 AND field4 = 19);

**Comment by legomolina** [comment]
There is a problem with andFilter and orFilter methods. If you pass them just 2 params, as they expect 3, throws a php error. Could making the last paramenter empty string be a solution?

**Comment by utking** [comment]
~Could you provide an example of what do you want to achieve? As I understand, 3 parameters is a requirement even for the current version of 'when', which was used for andFilter and orFilter.~
PS: I checked the code and made appropriate changes. I used NULL as the default since we must allow an empty string to be a filter value.

**Comment by utking** [comment]
Also I added not() to be able to create negations:

$result = MyModel::all()->where()
->andFilter([
['field1', '=', 'value'],
['field2', 'LIKE', '%a%'],
])
->or()
->not()
->andFilter([
['field3', '=', 18],
['field4', '=', 19],
])
->execute();
results to SELECT * FROM MyModel WHERE (field1 = 'value' AND field2 LIKE '%a%') OR NOT (field3 = 18 AND field4 = 19);

**Comment by utking** [comment]
Also I added isNull($field):

$result = MyModel::all()->where()->isNull('field1')->execute();
results to SELECT * FROM MyModel WHERE field1 IS NULL;

or negated

$result = MyModel::all()->where()->not()->isNull('field1')->execute();
results to SELECT * FROM MyModel WHERE NOT field1 IS NULL;

**Comment by legomolina** [comment]
I've have seen other problem.
```
public function orFilter($field, $operator = '=', $value = NULL)
{
    if (is_null($value))
        throw new Exc\InvalidORMArgument('Value must be provided');

    if (!is_array($field)) {
        $fields = [[$field, $operator, $value]];
    } else {
        $fields = $field;
    }

    return $this->whereFilter(self::WHERE_OR, $fields);
}
```

You are checking if $value is null but it always will be null if you pass only 1 param with some conditions. Also, can you use null instead of NULL?

Thanks!

**Comment by utking** [comment]
My bad. Changed NULL to null and added an additional check

**Pull request merged**
